CREATE TABLE Users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(30) NOT NULL UNIQUE,
  email VARCHAR(256) NOT NULL UNIQUE,
  hashedPassword BYTEA NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
  updatedAt TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE Notebooks (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  userId INTEGER NOT NULL REFERENCES Users(id) ON DELETE CASCADE,
  description TEXT,
  createdAt TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE Notes (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  notebookId INTEGER NOT NULL REFERENCES Notebooks(id) ON DELETE CASCADE,
  description TEXT,
  createdAt TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE Reminders (
  id SERIAL PRIMARY KEY,
  userId INTEGER NOT NULL REFERENCES Users(id) ON DELETE CASCADE,
  notesId INTEGER NOT NULL REFERENCES Notes(id) ON DELETE CASCADE,
  content TEXT,
  createdAt TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP NOT NULL
);
